from enum import Enum


class FieldDescriptionType(str, Enum):
    IMAGE_JPEG = "image/jpeg"
    IMAGE_PNG = "image/png"
    TEXT_PLAIN = "text/plain"
    TEXT_CSV = "text/csv"
    APPLICATION_JSON = "application/json"
    APPLICATION_PDF = "application/pdf"
    APPLICATION_ZIP = "application/zip"
    AUDIO_MP3 = "audio/mpeg"
    AUDIO_OGG = "audio/ogg"


class ExecutionUnitTagName(str, Enum):
    GENERIC = "Generic"
    IMAGE_PROCESSING = "Image Processing"
    IMAGE_RECOGNITION = "Image Recognition"
    IMAGE_GENERATION = "Image Generation"
    AUDIO_PROCESSING = "Audio Processing"
    AUDIO_GENERATION = "Audio Generation"
    VIDEO_PROCESSING = "Video Processing"
    VIDEO_GENERATION = "Video Generation"
    DOCUMENT_PROCESSING = "Document Processing"
    DOCUMENT_GENERATION = "Document Generation"
    DATA_PREPROCESSING = "Data Preprocessing"
    NATURAL_LANGUAGE_PROCESSING = "Natural Language Processing"
    ANOMALY_DETECTION = "Anomaly Detection"
    RECOMMENDATION = "Recommendation"
    TIME_SERIES = "Time Series"
    CLUSTERING = "Clustering"
    SEGMENTATION = "Segmentation"
    SPEECH_RECOGNITION = "Speech Recognition"
    SENTIMENT_ANALYSIS = "Sentiment Analysis"
    NEURAL_NETWORKS = "Neural Networks"


class ExecutionUnitTagAcronym(str, Enum):
    GENERIC = "GNR"
    IMAGE_PROCESSING = "IP"
    IMAGE_RECOGNITION = "IR"
    IMAGE_GENERATION = "IG"
    AUDIO_PROCESSING = "AP"
    AUDIO_GENERATION = "AG"
    VIDEO_PROCESSING = "VP"
    VIDEO_GENERATION = "VG"
    DOCUMENT_PROCESSING = "DP"
    DOCUMENT_GENERATION = "DG"
    DATA_PREPROCESSING = "DP"
    NATURAL_LANGUAGE_PROCESSING = "NLP"
    ANOMALY_DETECTION = "AD"
    RECOMMENDATION = "R"
    TIME_SERIES = "TS"
    CLUSTERING = "C"
    SEGMENTATION = "S"
    SPEECH_RECOGNITION = "SR"
    SENTIMENT_ANALYSIS = "SA"
    NEURAL_NETWORKS = "NN"
