# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: remove-unnecessary-keys-from-kubernetes-configuration-files
description: Remove unnecessary keys from kubernetes configuration files

inputs:
  configuration-files-location:
    description: Configuration files location for Kubernetes
    required: true
    default: .

runs:
  using: composite
  steps:
    - name: Prepare Kubernetes configuration files
      shell: bash
      working-directory: ${{ inputs.configuration-files-location }}
      run: |
        # Delete unnecessary service configuration keys (Ingress)
        yq -i "del(.metadata.annotations.cert-manager\.io/cluster-issuer)" ingress.yml
        yq -i "del(.spec.tls)" ingress.yml
        # Change ingress class name to nginx-ext
        yq -i ".spec.ingressClassName = \"nginx-ext\"" ingress.yml
