# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: execute_command_on_kubernetes_cluster
description: Execute a command on a Kubernetes cluster

inputs:
  kubectl-binary-url:
    description: kubectl binary URL
    required: true
    default: https://dl.k8s.io/release/v1.25.3/bin/linux/amd64/kubectl
  kubectl-binary-sha-url:
    description: kubectl binary SHA URL
    required: true
    default: https://dl.k8s.io/v1.25.3/bin/linux/amd64/kubectl.sha256
  kube-config:
    description: kubectl config file
    required: true
  kube-namespace:
    description: kubectl namespace
    required: true
  kubectl-context:
    description: kubectl context
    required: true
    default: .
  kubectl-args:
    description: kubectl arguments
    required: true

runs:
  using: composite
  steps:
    - name: Get filenames from URLs
      shell: bash
      run: |
        echo "KUBECTL_BINARY_NAME=$(basename "${{ inputs.kubectl-binary-url }}")" >> $GITHUB_ENV
        echo "KUBECTL_BINARY_SHA_NAME=$(basename "${{ inputs.kubectl-binary-sha-url }}")" >> $GITHUB_ENV

    - name: Download kubectl binary
      shell: bash
      run: curl -LO -s "${{ inputs.kubectl-binary-url }}"

    - name: Download kubectl binary SHA
      shell: bash
      run: curl -LO -s "${{ inputs.kubectl-binary-sha-url }}"

    - name: Verify kubectl binary with SHA checksum
      shell: bash
      run: echo "$(cat $KUBECTL_BINARY_SHA_NAME) kubectl" | sha256sum --check

    - name: Install kubectl binary
      shell: bash
      run: sudo install -o root -g root -m 0755 $KUBECTL_BINARY_NAME /usr/local/bin/kubectl

    - name: Create kubectl config file
      shell: bash
      run: |
        mkdir --parent ~/.kube
        echo "${{ inputs.kube-config }}" > ~/.kube/config

    - name: Execute kubectl command
      shell: bash
      working-directory: ${{ inputs.kubectl-context }}
      run: kubectl --namespace "${{ inputs.kube-namespace }}" ${{ inputs.kubectl-args }}
