# Documentation: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: prepare_kubernetes_configuration_files
description: Prepare Kubernetes configuration files

inputs:
  service-name:
    description: Name of the service
    required: true
  service-url:
    description: URL of the service
    required: true
  service-docker-image-tag:
    description: Docker image tag of the service
    required: true
  configuration-files-location:
    description: Configuration files location for Kubernetes
    required: true
    default: .
  environment:
    description: Environment of the service
    required: true
  log-level:
    description: Log level used by the service
    required: true
    default: info
  engine-urls:
    description: Engine URLs used by the service
    required: true
  max-tasks:
    description: Maximum number of tasks the service can accept
    required: true
  engine-announce-retries:
    description: Number of retries on the Engine for announcement
    required: true
  engine-announce-retry-delay:
    description: Delay between each retry
    required: true
  keda-service:
    description: KEDA service
    required: false
  keda-port:
    description: KEDA port
    required: false
    default: "8080"
  keda-min-replicas:
    description: KEDA minimum replicas
    required: false
    default: "0"
  keda-max-replicas:
    description: KEDA maximum replicas
    required: false
    default: "2"
  keda-scaledown-period:
    description: KEDA scale down period in seconds
    required: false
    default: "86400"
  keda-service-port:
    description: KEDA service port
    required: false
    default: "9090"

runs:
  using: composite
  steps:
    - name: Prepare Kubernetes configuration files
      shell: bash
      working-directory: ${{ inputs.configuration-files-location }}
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        LOG_LEVEL: ${{ inputs.log-level }}
        ENGINE_URLS: ${{ inputs.engine-urls }}
        SERVICE_URL: ${{ inputs.service-url }}
        MAX_TASKS: ${{ inputs.max-tasks }}
        ENGINE_ANNOUNCE_RETRIES: ${{ inputs.engine-announce-retries }}
        ENGINE_ANNOUNCE_RETRY_DELAY: ${{ inputs.engine-announce-retry-delay }}
        KEDA_SERVICE: ${{ inputs.keda-service }}
        KEDA_PORT: ${{ inputs.keda-port }}
        KEDA_MIN_REPLICAS: ${{ inputs.keda-min-replicas }}
        KEDA_MAX_REPLICAS: ${{ inputs.keda-max-replicas }}
        KEDA_SCALEDOWN_PERIOD: ${{ inputs.keda-scaledown-period }}
        KEDA_SERVICE_PORT: ${{ inputs.keda-service-port }}
      run: |
        # Set service configuration (ConfigMap)
        yq -i ".metadata.name = \"${{ inputs.service-name }}-config\"" config-map.yml
        yq -i ".metadata.labels.app = \"${{ inputs.service-name }}\"" config-map.yml
        yq -i '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' config-map.yml
        envsubst < config-map.yml > new-config-map.yml
        mv new-config-map.yml config-map.yml

        # Set service configuration (Ingress)
        yq -i ".metadata.name = \"${{ inputs.service-name }}-ingress\"" ingress.yml
        yq -i ".spec.rules[0].host = \"${SERVICE_URL#*://}\"" ingress.yml
        # If keda-service is set, use it in the backend service name
        if [ -n "$KEDA_SERVICE" ]; then
          yq -i ".spec.rules[0].http.paths[0].backend.service.name = \"$KEDA_SERVICE\"" ingress.yml
          yq -i ".spec.rules[0].http.paths[0].backend.service.port.number = $KEDA_PORT" ingress.yml
        else
          yq -i ".spec.rules[0].http.paths[0].backend.service.name = \"${{ inputs.service-name }}-service\"" ingress.yml
        fi
        yq -i ".spec.tls[0].hosts[0] = \"${SERVICE_URL#*://}\"" ingress.yml
        # replace . with - in service url and add -tls-cert at the end
        SECRET_NAME=$(echo "${SERVICE_URL#*://}" | sed 's/\./-/g' | sed 's/$/-tls-cert/')
        yq -i ".spec.tls[0].secretName = \"$SECRET_NAME\"" ingress.yml
        
        # Set KEDA configuration if keda-service is set
        if [ -n "$KEDA_SERVICE" ]; then
          yq -i ".metadata.name = \"${{ inputs.service-name }}-scaledobject\"" scaled-object.yml
          yq -i ".spec.hosts[0] = \"${SERVICE_URL#*://}\"" scaled-object.yml
          yq -i ".spec.scaleTargetRef.name = \"${{ inputs.service-name }}-stateful\"" scaled-object.yml
          yq -i ".spec.scaleTargetRef.service = \"${{ inputs.service-name }}-service\"" scaled-object.yml
          yq -i ".spec.scaleTargetRef.port = ${{ inputs.keda-service-port }}" scaled-object.yml
          yq -i ".spec.replicas.min = $KEDA_MIN_REPLICAS" scaled-object.yml
          yq -i ".spec.replicas.max = $KEDA_MAX_REPLICAS" scaled-object.yml
          yq -i ".spec.scaledownPeriod = $KEDA_SCALEDOWN_PERIOD" scaled-object.yml
        fi

        # Set service configuration (Service)
        yq -i ".metadata.name = \"${{ inputs.service-name }}-service\"" service.yml
        yq -i ".spec.selector.app = \"${{ inputs.service-name }}\"" service.yml

        # Set service configuration (StatefulSet)
        yq -i ".metadata.name = \"${{ inputs.service-name }}-stateful\"" stateful.yml
        yq -i ".metadata.labels.app = \"${{ inputs.service-name }}\"" stateful.yml
        yq -i ".spec.serviceName = \"${{ inputs.service-name }}\"" stateful.yml
        yq -i ".spec.selector.matchLabels.app = \"${{ inputs.service-name }}\"" stateful.yml
        yq -i ".spec.template.metadata.labels.app = \"${{ inputs.service-name }}\"" stateful.yml
        yq -i ".spec.template.spec.containers[0].name = \"${{ inputs.service-name }}\"" stateful.yml
        yq -i ".spec.template.spec.containers[0].image = \"${{ inputs.service-docker-image-tag }}\"" stateful.yml
        yq -i ".spec.template.spec.containers[0].envFrom[0].configMapRef.name = \"${{ inputs.service-name }}-config\"" stateful.yml
